apiVersion: v1
kind: Pod
metadata:
  name: app-prod-fiap
  labels:
    app: producao
    tier: frontend
    course: fiap
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-loadbalancer-fiap
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: producao
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
