apiVersion: v1
kind: Pod
metadata:
  name: webapp-aws
  labels:
    app: webapp
    env: aws-fiap
    course: cloud-computing
spec:
  containers:
  - name: webapp
    image: httpd:latest
    ports:
    - containerPort: 80
    env:
    - name: AMBIENTE
      value: "aws-producao"
    - name: REGION
      value: "us-east-1"
    - name: COURSE
      value: "FIAP-Cloud"
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  nodeSelector:
    kubernetes.io/os: linux
