apiVersion: v1
kind: Pod
metadata:
  name: pod-sem-label
  labels:
    ambiente: teste  # Rótulo diferente
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80