apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: segundo-pod
    curso: 2TCNPZ  
spec:
  containers:
    - name: nginx-container-1
      image: nginx:latest
      ports:
        - containerPort: 80