apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: segundo-pod
    curso: 2TCNPZ
spec:
  containers:
    - name: nginx-container-2
      image: nginx:latest
      ports:
        - containerPort: 85