apiVersion: v1
kind: Pod
metadata:
  name: backend-api-fiap
  labels:
    app: backend
    tier: api
    course: fiap
spec:
  containers:
  - name: api
    image: nginx:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-fiap
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-client-fiap
  labels:
    app: frontend
    course: fiap
spec:
  containers:
  - name: client
    image: busybox
    command: ['sleep', '3600']
