apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-fiap
  labels:
    app: webapp
    course: fiap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      course: fiap
  template:
    metadata:
      labels:
        app: webapp
        course: fiap
    spec:
      containers:
      - name: webapp
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: COURSE
          value: "FIAP-Kubernetes"

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service-fiap
spec:
  selector:
    app: webapp
    course: fiap
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
